# Generated by Django 5.2.9 on 2025-12-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(help_text='Name of the person reporting', max_length=255)),
                ('issue_type', models.CharField(choices=[('traffic', 'Traffic Issue'), ('waste', 'Waste Management'), ('energy', 'Energy/Power Issue'), ('other', 'Other')], help_text='Type of issue being reported', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('image', models.ImageField(blank=True, help_text='Optional image of the issue', null=True, upload_to='citizen_reports/%Y/%m/%d/')),
                ('location', models.CharField(help_text='Location of the issue', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the report', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Citizen Report',
                'verbose_name_plural': 'Citizen Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='api_citizen_created_1c7803_idx'), models.Index(fields=['issue_type', 'status'], name='api_citizen_issue_t_7d907c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnergyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_consumption', models.FloatField(help_text='Total energy consumption in kWh')),
                ('avg_power', models.FloatField(help_text='Average power usage in watts')),
                ('voltage_stats', models.JSONField(default=dict, help_text='Voltage statistics (min, max, avg)')),
                ('anomalies_detected', models.BooleanField(default=False, help_text='Whether anomalies were detected')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Energy Log',
                'verbose_name_plural': 'Energy Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_energyl_created_b626e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Full address of the location', max_length=500)),
                ('congestion_rate', models.FloatField(help_text='Traffic congestion rate (0-1 or percentage)')),
                ('flow_speed', models.IntegerField(help_text='Traffic flow speed in km/h')),
                ('delay_time', models.IntegerField(default=0, help_text='Delay time in minutes')),
                ('has_incident', models.BooleanField(default=False, help_text='Whether there are incidents')),
                ('incident_count', models.IntegerField(default=0, help_text='Number of incidents detected')),
                ('status_code', models.CharField(choices=[('CLEAR', 'Clear Traffic'), ('LIGHT', 'Light Traffic'), ('MODERATE', 'Moderate Traffic'), ('HEAVY', 'Heavy Traffic'), ('SEVERE', 'Severe Traffic')], help_text='Traffic status code', max_length=20)),
                ('status_color', models.CharField(help_text='Color code for status visualization', max_length=20)),
                ('analysis', models.TextField(help_text='Traffic analysis description')),
                ('recommendation', models.TextField(help_text='Recommended actions')),
                ('alternative_routes', models.JSONField(default=list, help_text='List of alternative route suggestions')),
                ('alert_content', models.TextField(blank=True, help_text='Alert notification content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Traffic Log',
                'verbose_name_plural': 'Traffic Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status_code'], name='api_traffic_created_03f8cc_idx'), models.Index(fields=['address', '-created_at'], name='api_traffic_address_9c8b5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_fill_level', models.FloatField(help_text='Average fill level percentage (0-100)')),
                ('critical_count', models.IntegerField(default=0, help_text='Number of bins at critical level')),
                ('warning_count', models.IntegerField(default=0, help_text='Number of bins at warning level')),
                ('warning_locations', models.JSONField(default=list, help_text='List of locations with warnings')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Waste Log',
                'verbose_name_plural': 'Waste Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_wastelo_created_2774d7_idx')],
            },
        ),
    ]
